
# This file was *autogenerated* from the file test_dnd_ability_rolls.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)
### separator line ###
from .context import sagednd
import sagednd.dnd_ability_rolls as dndrolls


def test_dnd_ability_roll_score():
    score = dndrolls.dnd_ability_roll_score([_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ])
    expectation = _sage_const_2 +_sage_const_3 +_sage_const_4 
    assert score == expectation

def test_get_dnd_ability_rolls():
    rolls = dndrolls.get_dnd_ability_rolls()
    element_length_expectation = _sage_const_4 
    assert _sage_const_4  == len(rolls[_sage_const_0 ])
    




